name: Deploy to VPS

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Setup Node.js untuk test (opsional)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      # 3. Install deps + test (opsional, bisa di-skip kalau belum ada test)
      - name: Install & Test
        run: |
          npm ci
          npm test || echo "⚠️ No tests defined, skipping"

      # 4. Upload source code ke VPS (exclude yang tidak perlu)
      - name: Upload source code to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOSTINGER_IP }}
          username: ${{ secrets.HOSTINGER_USER }}
          key: ${{ secrets.HOSTINGER_SSH_KEY }}
          source: ".,!node_modules,!*.env,!README.md,!tests,!.*"
          target: "/var/www/pks-api"
          overwrite: true

      # 5. Install deps + restart pm2 di VPS
      - name: Run PM2 on VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOSTINGER_IP }}
          username: ${{ secrets.HOSTINGER_USER }}
          key: ${{ secrets.HOSTINGER_SSH_KEY }}
          envs: MONGO_URI_PROD,JWT_SECRET,PORT_PROD,UPLOAD_DIR_PROD
          script: |
            cd /var/www/pks-api

            # Install dep fresh
            npm ci --omit=dev

            # Generate env production
            cat > .env.production <<EOF
            NODE_ENV=production
            PORT=${PORT_PROD}
            MONGO_URI=${MONGO_URI_PROD}
            JWT_SECRET=${JWT_SECRET}
            UPLOAD_DIR=${UPLOAD_DIR_PROD}
            EOF

            # Start/restart PM2
            pm2 start ecosystem.config.js --env production || pm2 restart pks-api --update-env
            pm2 save
